# This file is a template, and might need editing before it works on your project.
# Read more about this script on this blog post https://about.gitlab.com/2016/11/30/setting-up-gitlab-ci-for-android-projects/, by Greyson Parrelli
image: openjdk:8-jdk

variables:
  ANDROID_COMPILE_SDK: "26"
  ANDROID_BUILD_TOOLS: "27.0.2"
  
cache:
  paths:
    - android-sdk-linux/
    - ~/.gradle/

before_script:
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1
  - wget --quiet --output-document=android-sdk-tools.zip https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip
  - mkdir -p android-sdk-linux
  - unzip android-sdk-tools.zip -d android-sdk-linux
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=$PATH:$PWD/android-sdk-linux/platform-tools/
  - echo y | android-sdk-linux/tools/bin/sdkmanager --licenses
  - echo y | android-sdk-linux/tools/bin/sdkmanager "platform-tools"
  - echo y | android-sdk-linux/tools/bin/sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}"
  - echo y | android-sdk-linux/tools/bin/sdkmanager "build-tools;${ANDROID_BUILD_TOOLS}"
  - echo y | android-sdk-linux/tools/bin/sdkmanager "extras;google;m2repository"
  - echo y | android-sdk-linux/tools/bin/sdkmanager "extras;android;m2repository"
  - chmod +x ./gradlew
  # auto accept licenses
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"


stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
    - app/build/outputs/

unitTests:
  stage: test
  script:
    - ./gradlew test

deployBeta:
  stage: deploy
  variables:
    PUBLISHER_TRACK: "beta"
  only:
    - master
  script:
    - ./gradlew publishApkBetaRelease

deployProduction:
  stage: deploy
  variables:
    PUBLISHER_TRACK: "production"
  only:
    - release
  script:
    - ./gradlew publishApkProdRelease
