name: Deploy Alpha

on:
  push:
    branches:
      - feature/alpha-*

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Secrets
        run: |
          echo "$GOOGLE_SERVICES_JSON_BASE64" | base64 --decode > app/google-services.json
          echo "$SERVICE_ACCOUNT_JSON_BASE64" | base64 --decode > play-service-account.json
        env:
          GOOGLE_SERVICES_JSON_BASE64: ${{ secrets.GOOGLE_SERVICES_JSON }}
          SERVICE_ACCOUNT_JSON_BASE64: ${{ secrets.SERVICE_ACCOUNT_JSON }}

      - name: Assemble Release Bundle
        run: |
          ./gradlew bundleRelease

      - name: Sign Android Release
        uses: r0adkll/sign-android-release@master
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Deploy Alpha
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: play-service-account.json
          packageName: com.r0adkll.deckbuilder
          releaseFile: ${{ env.SIGNED_RELEASE_FILE }}
          track: alpha
          whatsNewDirectory: distribution/
          mappingFile: app/build/outputs/mapping/release/mapping.txt
