name: Deploy Alpha

on:
  push:
    branches:
      - feature/*

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Dependency Check
        run: |
          echo $ANDROID_HOME
          echo "== Checking Build Tools =="
          ls -la $ANDROID_HOME/build-tools/29.0.2

      - name: Setup Secrets
        run: |
          echo "$GOOGLE_SERVICES_JSON_BASE64" | base64 --decode > app/google-services.json
        env:
          GOOGLE_SERVICES_JSON_BASE64: ${{ secrets.GOOGLE_SERVICES_JSON }}

      - name: Assemble Release APK
        run: |
          ./gradlew assembleRelease

      - name: Sign Android Release
        uses: r0adkll/sign-android-release@master
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
